import type { Metadata } from "next";
import { Josefin_Sans, Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import Providers from "./configs/Providers";

const montserrat = Montserrat({
  variable: "--montserrat-font",
  weight: ["400", "700"],
  display: "swap",
  subsets: ["latin"],
});

const josefinSans = Josefin_Sans({
  variable: "--josefin-sans-font",
  weight: ["400", "700"],
  display: "swap",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--roboto-font",
  weight: ["400", "700"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        style={{ height: "100vh", position: "relative" }}
        className={`${montserrat.variable} ${josefinSans.variable} ${roboto.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
