import type { Metadata } from "next";
import { Container, Grid, GridItem } from "@chakra-ui/react";
import SideBarDashboard from "@/components/custom/dashboard/SideBar/SideBarDashboard";
import "../../styles/dashboard-layout.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Grid className="sidebar-dashboard-layout" height="100%">
      <SideBarDashboard />
      <GridItem bg="backgroundLight">
        <Container maxW="11/12" my={12}>
          {children}
        </Container>
      </GridItem>
    </Grid>
  );
}
