import { Box, Flex, Grid, GridItem, Heading, Text } from "@chakra-ui/react";
import { Metadata } from "next";
import { FaArrowRight } from "react-icons/fa6";

export const metadata: Metadata = {
  title: "My Dashboard",
  description: "Generated by create next app",
};

export default function DashboardPage() {
  return (
    <Box>
      <Flex justifyContent="space-between">
        <Box>
          <Heading size="4xl" className="font-montserrat">
            Welcome back, Sergiu
          </Heading>
          <Heading color="text" size="md">
            It&apos;s good to have you back
          </Heading>
        </Box>
      </Flex>

      <Grid templateColumns="repeat(6, 1fr)" mt={8}>
        <GridItem colSpan={3}>
          <Box
            width="100%"
            height="100px"
            bgColor="white"
            boxShadow="xs"
            px={6}
            py={4}
            position="relative"
          >
            <Flex justifyContent="space-between">
              <Text>Test</Text>
              <Flex
                position="absolute"
                right="20px"
                cursor="pointer"
                gap={1}
                _hover={{ gap: 2, color: "blackAlpha.700" }}
                alignItems="center"
                fontSize="xs"
              >
                <Text fontWeight="bold">Revolut Transactions</Text>
                <FaArrowRight />
              </Flex>
            </Flex>
          </Box>
        </GridItem>
      </Grid>
    </Box>
  );
}
